# Configuración básica del sitio
title: "Ana Alcázar Cobo"
description: "Videogame Programmer, Videogame Artist & Videogame Designer"
baseurl: ""
url: "https://ana-alcazar-cobo.com" # La URL completa de tu sitio
lang: "es" # Idioma del sitio
timezone: "Spain/Barcelona" # Ajustar según tu zona horaria
